name: pull-request-merger

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '50'

      - name: Skywater PDK Libraries Pull Request Merger on Release Branches
        uses: google/skywater-pdk-actions@main
